#pragma once

namespace GameLayer
{

enum
{
  LAYER_DEFAULT,
  LAYER_TIME,
  LAYER_GACHA,

  LAYER_PLAYER_0_BODY,
  LAYER_PLAYER_1_BODY,
  LAYER_PLAYER_2_BODY,
  LAYER_PLAYER_3_BODY,
  LAYER_PLAYER_4_BODY,
  LAYER_PLAYER_5_BODY,
  LAYER_PLAYER_6_BODY,
  LAYER_PLAYER_7_BODY,
  LAYER_PLAYER_8_BODY,
  LAYER_PLAYER_9_BODY,

  LAYER_PLAYER_0,
  LAYER_PLAYER_1,
  LAYER_PLAYER_2,
  LAYER_PLAYER_3,
  LAYER_PLAYER_4,
  LAYER_PLAYER_5,
  LAYER_PLAYER_6,
  LAYER_PLAYER_7,
  LAYER_PLAYER_8,
  LAYER_PLAYER_9,

  LAYER_DATANUM,
};

}